name: Build and deploy documentation
on:
  push:
    branches: gh-pages-doc # TODO: change to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Bender and Morty
        run: |
          rustup update stable --no-self-update && rustup default stable
          cargo install bender --version 0.18.0
          cargo install morty --version 0.5.0
        shell: bash

      - name: Build documentation
        run: |
          morty -I include -I $(bender path common_cells)/include src/*.sv -d docs
        shell: bash

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
