variables:
  VSIM: vsim-10.6b -64
  VLIB: vlib-10.6b
  VLOG: vlog-10.6b -64
  SYNOPSYS_DC: synopsys-2016.03 dc_shell -64bit

before_script:
  - export PATH=~fschuiki/.cargo/bin:$PATH
  - mkdir -p build

modelsim:
  script:
    - >
      if ! memora lookup vsim; then
        cd build && ../scripts/compile_vsim.sh
        memora insert vsim
      fi

synopsys:
  script:
    - cd build
    - ../scripts/synth.sh
